### ISSUE TITLE
dotnet  IReaderConfiguration.HasHeaderRecord

### ISSUE THREAD

**Issue by miksch27** [schletz/Dbi2Sem#1]
Ich bekomme beim Aufrufen des Befehls folgende Fehlermeldung.  Wo liegt hier die Ursache? Danke!

PS C:\Users\Chris\Dokumente\GitHub\Dbi2Sem\SchulDbGenerator\SchulDbGenerator> dotnet run -c Release 
Untisdata.cs(46,21): error CS0200: Für die Eigenschaft oder den Indexer "IReaderConfiguration.HasHeaderRecord" ist eine Zuweisung nicht möglich. Sie sind schreibgeschützt. [C:\Users\Chris\Dokumente\GitHub\Dbi2Sem\SchulDbGenerator\SchulDb.Untis\SchulDb.Untis.csproj]
Untisdata.cs(47,21): error CS0200: Für die Eigenschaft oder den Indexer "IParserConfiguration.Delimiter" ist eine Zuweisung 
nicht möglich. Sie sind schreibgeschützt. [C:\Users\Chris\Dokumente\GitHub\Dbi2Sem\SchulDbGenerator\SchulDb.Untis\SchulDb.Untis.csproj]

Fehler beim Buildvorgang. Beheben Sie die Buildfehler, und versuchen Sie es anschließend noch mal.

**Comment by schletz** [comment]
Danke für die Info. CSVHelper verwendet in der neuesten Version C# 9 Records für die Konfiguration. Der Code wurde angepasst.
